<?php if ($this->getFacebookAppID()) : ?>
<meta property="fb:app_id" content="<?php echo $this->getFacebookAppID(); ?>"/>
<?php endif; ?>
<?php if ($this->getFacebookAdminID()) : ?>
<meta property="fb:admins" content="<?php echo $this->getFacebookAdminID(); ?>" />
<?php endif; ?>
<meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl();?>"/>
<meta property="og:type" content="product"/>
<?php $product = Mage::registry('current_product');
if ($product): ?>
<meta property="og:title" content="<?php echo $this->htmlEscape($product->getName()); ?>"/>
<meta property="og:image" content="<?php echo Mage::helper('catalog/image')->init($product, 'image');?>"/>
<?php endif; ?>
