<?php
/**
 * Miragedesign Web Development
 *
 * @category    Miragedesign
 * @package     Miragedesign_Pinterest
 * @copyright   Copyright (c) 2011 Mirage Design (http://miragedesign.net)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */ 
?>
<?php if ($this->getIsEnabled() && $this->getIsVerticalScrollbarEnabled()) :?>
<?php	
	$productUrl = $this->getProductUrl();
	$productImage = $this->getProductImage();
	$productDescription = $this->getProductDescription();
	
	/*Get the current product count on Pinterest*/
	$pinterestCount = $this->getPinterestCount();
?>
<style type="text/css">
ul.vertical-social-bar {width: 90px; display: block; position: fixed; top: 100px; left: 115px;}
ul.vertical-social-bar li {text-align:center;}
ul.vertical-social-bar li div.fb-like {width:48px;}
</style>
<ul class="vertical-social-bar">
<li>
<a href="http://pinterest.com/pin/create/button/?url=<?php echo $productUrl; ?>&media=<?php echo $productImage; ?>&description=<?php echo $productDescription; ?>" class="pin-it-button" count-layout="<?php echo $pinterestCount; ?>"><?php echo $this->helper('pinterest')->__('Pin It'); ?></a>
<script type="text/javascript" src="http://assets.pinterest.com/js/pinit.js"></script>
</li>
<?php if ($this->checkFacebookIsEnabled()) :?>
<li>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-like" data-href="<?php echo $productUrl ?>" data-send="false" data-layout="box_count" data-width="50" data-show-faces="false"></div>
</li>	
<?php endif; ?>

<?php if ($this->checkTwitterIsEnabled()) :?>
<li>
<a href="https://twitter.com/share" class="twitter-share-button" data-url="<?php echo $productUrl ?>" data-via="Pinteresttuto" data-count="vertical">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</li>
<?php endif; ?>

<?php if ($this->checkGooglePlusIsEnabled()) :?>
<li>
<!-- Place this tag where you want the +1 button to render -->
<g:plusone size="tall" href="<?php echo $productUrl; ?>"></g:plusone>
<!-- Place this render call where appropriate -->
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
</li>
<?php endif; ?>
<?php if ($this->checkLinkedInIsEnabled()) :?>
<script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
<li>
<script type="IN/Share" data-counter="top"></script>
</li>
<?php endif; ?>

<?php if ($this->checkDiggIsEnabled()) :?>
<script type="text/javascript">
(function() {
var s = document.createElement('SCRIPT'), s1 = document.getElementsByTagName('SCRIPT')[0];
s.type = 'text/javascript';
s.async = true;
s.src = 'http://widgets.digg.com/buttons.js';
s1.parentNode.insertBefore(s, s1);
})();
</script>
<li><a class="DiggThisButton DiggMedium"></a></li>
<?php endif; ?>


</ul>
<?php endif; ?>